# Generated by Django 4.0.3 on 2022-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_class', models.CharField(max_length=50, verbose_name='property_class')),
                ('property_status', models.CharField(max_length=50, verbose_name='property_status')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='neighborhood')),
                ('location', models.CharField(max_length=150, verbose_name='neighborhood')),
                ('latitude_pinpoint', models.FloatField(verbose_name='latitude_pinpoint')),
                ('longitude_pinpoint', models.FloatField(verbose_name='longitude_pinpoint')),
                ('year_of_acquisition', models.IntegerField(verbose_name='year_of_acquisition')),
                ('latitude_street', models.FloatField(verbose_name='latitude_street')),
                ('longitude_street', models.FloatField(verbose_name='longitude_street')),
                ('frontview_heading', models.IntegerField(verbose_name='frontview_heading')),
                ('panoids_years', models.CharField(max_length=500, verbose_name='panoids_years')),
            ],
        ),
    ]
